WIDTH = 1200
HEIGHT = 700
INDENT = 10

BACKGROUND_COLOR = "#FFFFFF"
CORRECT_COLOR = "#32CD32"
INCORRECT_COLOR = "#FF0000"
NEUTRAL_COLOR = "#696969"

FONT_NAME = "Consolas"
SIDE_FONT_SIZE = 20
MAIN_FONT_SIZE = 35

MAX_SYMBOLS_IN_LINE = (WIDTH - INDENT) // MAIN_FONT_SIZE

DEFAULT_PATH = "./texts/"

START_BUTTON_BACKGROUND_COLOR = "#32CD32"
START_BUTTON_FONT_SIZE = 30

RETRY_BUTTON_BACKGROUND_COLOR = "#F08080"
RETRY_BUTTON_FONT_SIZE = 15
RETRY_PAD = 20
