WIDTH = 1200
HEIGHT = 700
INDENT = 10

BACKGROUND_COLOR = "#FFFFFF"
CORRECT_COLOR = "#32CD32"
INCORRECT_COLOR = "#FF0000"
NEUTRAL_COLOR = "#696969"

FONT_NAME = "Consolas"
SIDE_FONT_SIZE = 20
MAIN_FONT_SIZE = 35
LINES_PADY = 30

MAX_SYMBOLS_IN_LINE = (WIDTH - INDENT) // MAIN_FONT_SIZE

DEFAULT_PATH = "./texts/"

START_BUTTON_BACKGROUND_COLOR = "#32CD32"
START_BUTTON_FONT_SIZE = 30

RETRY_BUTTON_BACKGROUND_COLOR = "#F08080"
RETRY_BUTTON_FONT_SIZE = 15
RETRY_PAD = 20

LOAD_FILE_BUTTON_BACKGROUND_COLOR = "#FFEBCD"
LOAD_FILE_FONT_SIZE = 14

SECONDS_PER_MINUTE = 60
STATS_PATH = "./bin/statistics.txt"
STATS_COLOR = "#228B22"
STATS_UPDATE_FREQUENCY = 50  # every ?? ticks
STATS_FONT_SIZE = 30

ADD_CHOOSE_FRAME_PADX = HEIGHT // 8
ADD_CHOOSE_FONT_SIZE = 16

DEFAULT_PADX = 5

AVAILABLE_LANGUAGES = ["russian", "english"]
DEFAULT_LANGUAGE = "russian"


MAIN_WORD_FONT_SIZE = 100
MAIN_WORD_PADY = HEIGHT // 7
